### ISSUE TITLE
Add the `openapi3` tag to this repository

### ISSUE THREAD

**Issue by waldyrious** [robertlove/jekyll-openapi#4]
This project is awesome and I wish more people were aware of it, especially those with the know-how to contribute. Adding the [`openapi3`](https://github.com/topics/openapi3) tag helps it be more discoverable (and in particular, it allows it to be picked up by the directory of OpenAPI tools at https://apis.guru/awesome-openapi3/). 🙂

**Comment by robertlove** [comment]
Hi @waldyrious

Thanks for the feedback and the requests in the other issues raised. I agree there's potential in this project and I'd love others to contribute as I no longer have the time. If you'd like to suggest changes please feel free to submit a PR.

Cheers,
Robert

**Comment by waldyrious** [comment]
Totally understand, and I'd be happy to submit any changes I'm able to contribute. This one in particular can only be done by you, though, as a repo admin. You should see a gear icon next to the "About" section at the top of the sidebar in the repo homepage. I don't think even collaborators can do that.

While we're at it, I do think the summary in the README:

> An OpenAPI 3 documentation website generator built with Jekyll for use on GitHub Pages

...is more explicit and compelling than the one currently used as the repository description:

> A starter Jekyll site for generating OpenAPI 3 documentation 

so I'd suggest also taking the opportunity to align both to the same wording :)

**Comment by waldyrious** [comment]
By the way, since we're talking about discoverability, I thought I'd let you know that I [created a PR](https://github.com/apisyouwonthate/openapi.tools/pull/236) adding this tool to the [OpenAPI.tools directory](https://openapi.tools/) (whose contents are manually curated, unlike the list from `apis.guru` which uses a hybrid model).

**Comment by robertlove** [comment]
@waldyrious sorry for taking so long to get to this. I've actioned your suggestions. Thanks for the support. And don't be shy with any PRs. If you think this project has legs, it would be good to get it running! :)

**Comment by waldyrious** [comment]
No worries @robertlove, I know how other priorities can often get in the way of open source projects :)

Along the lines of the changes implemented here, I would suggest you to install https://github.com/probot/settings in this repo, which would allow such configurations to be both source-tracked and contributable via PRs. (Note that you don't need to create the `.github/settings.yml` file upon installing the app — I'd be happy to contribute that file via a PR afterwards.)
